version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "80:80"
    environment:
      - NODE_ENV=e2e

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
      args:
        - OPENAI_API_KEY_JANET=${OPENAI_API_KEY_JANET}
        - JANET_SEG_BOT_TOKEN=${JANET_SEG_BOT_TOKEN}
        - JANET_SEG_BOT_CHAT_ID=${JANET_SEG_BOT_CHAT_ID}
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY_JANET=${OPENAI_API_KEY_JANET}
      - JANET_SEG_BOT_TOKEN=${JANET_SEG_BOT_TOKEN}
      - JANET_SEG_BOT_CHAT_ID=${JANET_SEG_BOT_CHAT_ID}
      - FLASK_APP=server.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PORT=8080

  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    depends_on:
      - frontend
      - server
