services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-alt.address=:8082"
    ports:
      - "80:80"     # Web
      - "8080:8080" # Dashboard (default)
      - "8082:8082" # Web-alt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`localhost`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web-alt"

  frontend:
    build: ./frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`) && !PathPrefix(`/api/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  backend:
    build: ./server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web,web-alt"
      - "traefik.http.services.backend.loadbalancer.server.port=23925"
    environment:
      - FLASK_ENV=production
      - PORT=23925
      - OPENAI_API_KEY_JANET=${OPENAI_API_KEY_JANET}
      - JANET_SEG_BOT_TOKEN=${JANET_SEG_BOT_TOKEN}
      - JANET_SEG_BOT_CHAT_ID=${JANET_SEG_BOT_CHAT_ID}
    volumes:
      - ./server:/app
    networks:
      - app-network

  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    depends_on:
      - traefik
      - frontend
      - backend
    environment:
      - CI=${CI:-false}
      - PLAYWRIGHT_TEST_BASE_URL=http://traefik
      - DEBUG=pw:api
    ipc: host
    networks:
      - app-network
    volumes:
      - ./e2e/test-results:/e2e/test-results
      - ./e2e/playwright-report:/e2e/playwright-report
      - ./e2e/tests:/e2e/tests

networks:
  app-network:
    driver: bridge