version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  backend:
    build: ./server
    ports:
      - "23925:23925"
    environment:
      - FLASK_ENV=production
      - OPENAI_API_KEY_JANET=${OPENAI_API_KEY_JANET}
      - DEBUG_MODE=${DEBUG_MODE:-false}
    volumes:
      - ./server:/app
    networks:
      - app-network

  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    environment:
      - CI=${CI:-false}
      - PLAYWRIGHT_TEST_BASE_URL=http://frontend
      - DEBUG=pw:api
    ipc: host
    networks:
      - app-network
    volumes:
      - ./e2e/test-results:/e2e/test-results
      - ./e2e/playwright-report:/e2e/playwright-report
      - ./e2e/tests:/e2e/tests

networks:
  app-network:
    driver: bridge
