version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "80:80"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY_JANET}
      - JANET_SEG_BOT_TOKEN=${JANET_SEG_BOT_TOKEN}
      - JANET_SEG_BOT_CHAT_ID=${JANET_SEG_BOT_CHAT_ID}
      - PORT=8080  # Make the server listen on port 8080 in CI

  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    depends_on:
      - frontend
      - server
