---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-spidamar-janet-secrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
  managedSecret:
    name: janet-secrets
    namespace: janet
    type: Opaque
  secrets:
    - OPENAI_API_KEY_JANET
    - JANET_SEG_BOT_TOKEN
    - JANET_SEG_BOT_CHAT_ID