---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: doppler-spidamar-janet-secrets
  namespace: janet
spec:
  project: spidamar
  config: prd
  host: https://api.doppler.com
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  managedSecret:
    name: janet-secrets
    namespace: janet
    type: Opaque
  resyncSeconds: 60
  secrets:
    - OPENAI_API_KEY_JANET
    - JANET_SEG_BOT_TOKEN
    - JANET_SEG_BOT_CHAT_ID
  verifyTLS: true