name: Docker Build and Push

on:
  workflow_call:
    inputs:
      platform:
        description: 'Platform to build for'
        required: true
        type: string
    secrets:
      token:
        required: true

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend
  BACKEND_IMAGE_NAME: ${{ github.repository }}-backend
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      - name: Get versions
        id: versions
        run: |
          echo "FRONTEND_VERSION=$(cat frontend/version.txt)" >> $GITHUB_ENV
          echo "BACKEND_VERSION=$(cat server/version.txt)" >> $GITHUB_ENV

      - name: Cache Frontend Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-frontend
          key: ${{ runner.os }}-buildx-frontend-${{ hashFiles('frontend/**') }}
          restore-keys: |
            ${{ runner.os }}-buildx-frontend-

      - name: Cache Backend Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache-backend
          key: ${{ runner.os }}-buildx-backend-${{ hashFiles('server/**') }}
          restore-keys: |
            ${{ runner.os }}-buildx-backend-

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          platforms: ${{ inputs.platform }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ env.FRONTEND_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache-frontend
          cache-to: type=local,dest=/tmp/.buildx-cache-frontend-new,mode=max
          provenance: false
          build-args: |
            VERSION=${{ env.FRONTEND_VERSION }}

      - name: Move Frontend cache
        run: |
          rm -rf /tmp/.buildx-cache-frontend
          mv /tmp/.buildx-cache-frontend-new /tmp/.buildx-cache-frontend

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          platforms: ${{ inputs.platform }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ env.BACKEND_VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache-backend
          cache-to: type=local,dest=/tmp/.buildx-cache-backend-new,mode=max
          provenance: false
          build-args: |
            VERSION=${{ env.BACKEND_VERSION }}

      - name: Move Backend cache
        run: |
          rm -rf /tmp/.buildx-cache-backend
          mv /tmp/.buildx-cache-backend-new /tmp/.buildx-cache-backend

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: v${{ env.BACKEND_VERSION }}
