name: E2E Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DEBUG_MODE: true

    steps:
    - uses: actions/checkout@v3

    - name: Build and run containers
      run: |
        docker compose build
        docker compose up -d

    - name: Run Playwright tests
      run: |
        cd e2e
        npm ci
        npx playwright install --with-deps
        npm test

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: e2e/playwright-report/
        retention-days: 30
