name: E2E Setup

on:
  workflow_call:
    inputs:
      platform:
        description: "Platform to build for"
        required: false
        type: string
        default: "linux/amd64"
    secrets:
      OPENAI_API_KEY_JANET:
        required: true
      JANET_SEG_BOT_TOKEN:
        required: true
      JANET_SEG_BOT_CHAT_ID:
        required: true

env:
  DOCKER_BUILDKIT: 1
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY_JANET }}
  JANET_SEG_BOT_TOKEN: ${{ secrets.JANET_SEG_BOT_TOKEN }}
  JANET_SEG_BOT_CHAT_ID: ${{ secrets.JANET_SEG_BOT_CHAT_ID }}
  DEBUG_MODE: true
  CI: true
  DOCKER_DEFAULT_PLATFORM: ${{ inputs.platform }}

jobs:
  setup-and-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      if: inputs.platform == 'linux/arm64'
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-flags: --debug
        driver-opts: |
          image=moby/buildkit:latest
          network=host

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Cache Playwright dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/ms-playwright
          e2e/node_modules
        key: ${{ runner.os }}-playwright-${{ hashFiles('e2e/package*.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-
        retention-days: 7

    - name: Build Frontend with GHCR cache
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        load: true
        tags: social-engineering-game-frontend:test
        cache-from: |
          type=registry,ref=ghcr.io/${{ github.repository }}/frontend-cache:latest
          type=local,src=/tmp/.buildx-cache-frontend
        cache-to: |
          type=registry,ref=ghcr.io/${{ github.repository }}/frontend-cache:latest,mode=max
          type=local,dest=/tmp/.buildx-cache-frontend,mode=max
        build-args: |
          VERSION=test
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY_JANET }}

    - name: Build Backend with GHCR cache
      uses: docker/build-push-action@v4
      with:
        context: ./server
        load: true
        tags: social-engineering-game-backend:test
        cache-from: |
          type=registry,ref=ghcr.io/${{ github.repository }}/backend-cache:latest
          type=local,src=/tmp/.buildx-cache-backend
        cache-to: |
          type=registry,ref=ghcr.io/${{ github.repository }}/backend-cache:latest,mode=max
          type=local,dest=/tmp/.buildx-cache-backend,mode=max
        build-args: |
          VERSION=test
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY_JANET }}
          JANET_SEG_BOT_TOKEN=${{ secrets.JANET_SEG_BOT_TOKEN }}
          JANET_SEG_BOT_CHAT_ID=${{ secrets.JANET_SEG_BOT_CHAT_ID }}

    - name: Start containers
      run: |
        docker compose -f docker-compose.ci.yml up -d

    - name: Wait for services to be ready
      run: |
        echo "Waiting for containers to start..."
        docker ps

        echo "Waiting for frontend..."
        ./scripts/wait-for.sh -t 60 localhost:80:http:///health || {
          echo "Frontend failed to become ready. Showing logs:"
          docker compose -f docker-compose.ci.yml logs
          exit 1
        }

        echo "Waiting for backend..."
        ./scripts/wait-for.sh -t 60 localhost:8080:http:///api/health || {
          echo "Backend failed to become ready. Showing logs:"
          docker compose -f docker-compose.ci.yml logs
          exit 1
        }

    - name: Run Playwright tests
      run: |
        cd e2e
        npm ci
        npx playwright install --with-deps chromium
        PLAYWRIGHT_TEST_BASE_URL=http://localhost npm test

    - name: Upload Playwright test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: |
          e2e/playwright-report/
          e2e/test-results/
        retention-days: 30

    - name: Stop containers
      if: always()
      run: docker compose -f docker-compose.ci.yml down --remove-orphans

    - name: Cleanup GHCR caches
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Cleaning up outdated GHCR caches..."
        # Using GitHub API to manage package versions
        gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /user/packages/container/frontend-cache/versions --jq '.[] | select(.metadata.container.tags | index("latest") | not) | .id' | \
          xargs -I {} gh api --method DELETE /user/packages/container/frontend-cache/versions/{} || true
        
        gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /user/packages/container/backend-cache/versions --jq '.[] | select(.metadata.container.tags | index("latest") | not) | .id' | \
          xargs -I {} gh api --method DELETE /user/packages/container/backend-cache/versions/{} || true