name: PR Tests

on:
  pull_request:
    branches:
      - master  # Only run on PRs targeting master
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  test:
    uses: ./.github/workflows/e2e-setup.yml
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
