name: PR Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main  # Only run on PRs targeting main
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  test:
    uses: ./.github/workflows/e2e-setup.yml
    with:
      platform: 'linux/amd64'  # Only test AMD64 for PRs
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_API_KEY_JANET: ${{ secrets.OPENAI_API_KEY_JANET }}
      JANET_SEG_BOT_TOKEN: ${{ secrets.JANET_SEG_BOT_TOKEN }}
      JANET_SEG_BOT_CHAT_ID: ${{ secrets.JANET_SEG_BOT_CHAT_ID }}
