name: Tests AMD64

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  test-amd64:
    uses: ./.github/workflows/e2e-setup.yml
    with:
      platform: 'linux/amd64'
    secrets:
      OPENAI_API_KEY_JANET: ${{ secrets.OPENAI_API_KEY_JANET }}
      JANET_SEG_BOT_TOKEN: ${{ secrets.JANET_SEG_BOT_TOKEN }}
      JANET_SEG_BOT_CHAT_ID: ${{ secrets.JANET_SEG_BOT_CHAT_ID }}

  release-arm:
    needs: test-amd64
    if: ${{ success() }}
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/docker-publish.yml
    with:
      platform: 'linux/arm64'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
