name: Tests AMD64

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  test-amd64:
    uses: ./.github/workflows/e2e-setup.yml
    with:
      platform: 'linux/amd64'
    secrets:
      OPENAI_API_KEY_JANET: ${{ secrets.OPENAI_API_KEY_JANET }}
      JANET_SEG_BOT_TOKEN: ${{ secrets.JANET_SEG_BOT_TOKEN }}
      JANET_SEG_BOT_CHAT_ID: ${{ secrets.JANET_SEG_BOT_CHAT_ID }}
