name: Push Tests

on:
  push:
    branches:
      - master  # For pushes to master (after merges)
      - 'test-ci*'  # For our test branches
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  test:
    uses: ./.github/workflows/e2e-setup.yml
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
