name: Tests AMD64

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

jobs:
  setup-and-test:  # This must match the job name in e2e-setup.yml
    uses: ./.github/workflows/e2e-setup.yml
    with:
      platform: 'linux/amd64'
    secrets:
      OPENAI_API_KEY_JANET: ${{ secrets.OPENAI_API_KEY_JANET }}
      JANET_SEG_BOT_TOKEN: ${{ secrets.JANET_SEG_BOT_TOKEN }}
      JANET_SEG_BOT_CHAT_ID: ${{ secrets.JANET_SEG_BOT_CHAT_ID }}

  build-and-push:  # This must match the job name in docker-publish.yml
    needs: setup-and-test
    if: ${{ success() }}
    uses: ./.github/workflows/docker-publish.yml
    with:
      platform: 'linux/arm64'
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
