name: Push Tests

on:
  push:
    branches:
      - master
    # paths-ignore:
    #   - '**.md'
    #   - 'docs/**'
  workflow_dispatch:

jobs:
  test-amd64:
    uses: ./.github/workflows/e2e-setup.yml
    with:
      platform: 'linux/amd64'
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
